from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path, PurePosixPath
import posixpath
import tomllib
from typing import Any, Iterator, Mapping

import tomlkit

from .config import SyncConfig
from .errors import SyncError


GENERATED_HEADER = """\
# Generated by tooling/zed-gpui-sync. Do not edit by hand.
# This is a reduced projection of Zed's root Cargo.toml.

"""
TRANSITIVE_GPUI_PATCHES = {"async-process", "windows-capture"}
DEPENDENCY_TABLES = ("dependencies", "dev-dependencies", "build-dependencies")


@dataclass(frozen=True, slots=True)
class GeneratedWorkspace:
    content: str
    members: tuple[Path, ...]
    workspace_dependencies: tuple[str, ...]


def _load_toml(path: Path) -> dict[str, Any]:
    try:
        with path.open("rb") as file:
            return tomllib.load(file)
    except FileNotFoundError as error:
        raise SyncError(f"required Cargo manifest is missing: {path}") from error
    except tomllib.TOMLDecodeError as error:
        raise SyncError(f"invalid TOML in {path}: {error}") from error


def _safe_source_path(value: object, *, description: str) -> Path:
    if not isinstance(value, str) or not value.strip():
        raise SyncError(f"{description} must be a non-empty path string")
    pure_path = PurePosixPath(value)
    if pure_path.is_absolute() or pure_path == PurePosixPath("."):
        raise SyncError(f"{description} is not a safe repository-relative path: {value!r}")
    if ".." in pure_path.parts:
        raise SyncError(f"{description} is not a safe repository-relative path: {value!r}")
    return Path(*pure_path.parts)


def _resolve_dependency_path(member: Path, value: object) -> Path:
    if not isinstance(value, str) or not value.strip():
        raise SyncError(f"dependency path in {member / 'Cargo.toml'} must be a string")
    raw = PurePosixPath(value)
    if raw.is_absolute():
        raise SyncError(f"dependency path must be repository-relative: {value!r}")
    normalized = posixpath.normpath((PurePosixPath(member) / raw).as_posix())
    if normalized == "." or normalized == ".." or normalized.startswith("../"):
        raise SyncError(f"dependency path escapes the Zed repository: {value!r}")
    return Path(*PurePosixPath(normalized).parts)


def _dependency_tables(manifest: Mapping[str, Any]) -> Iterator[Mapping[str, Any]]:
    for table_name in DEPENDENCY_TABLES:
        table = manifest.get(table_name, {})
        if isinstance(table, Mapping):
            yield table

    targets = manifest.get("target", {})
    if isinstance(targets, Mapping):
        for target in targets.values():
            if not isinstance(target, Mapping):
                continue
            for table_name in DEPENDENCY_TABLES:
                table = target.get(table_name, {})
                if isinstance(table, Mapping):
                    yield table


def _covered_by_mirror_path(member: Path, mirror_paths: tuple[Path, ...]) -> bool:
    return any(member == path or path in member.parents for path in mirror_paths)


def _multiline_array(values: list[str]) -> Any:
    result = tomlkit.array()
    result.multiline(True)
    for value in values:
        result.append(value)
    return result


def generate_workspace_manifest(checkout: Path, config: SyncConfig) -> GeneratedWorkspace:
    """Project Zed's workspace manifest onto GPUI's dependency closure."""

    source_manifest = checkout / config.workspace_manifest_path
    root = _load_toml(source_manifest)
    workspace = root.get("workspace")
    if not isinstance(workspace, Mapping):
        raise SyncError(f"{config.workspace_manifest_path} has no [workspace] table")
    root_dependencies = workspace.get("dependencies")
    if not isinstance(root_dependencies, Mapping):
        raise SyncError(
            f"{config.workspace_manifest_path} has no [workspace.dependencies] table"
        )

    required_workspace_dependencies: set[str] = set(config.workspace_packages)
    all_dependency_names: set[str] = set(config.workspace_packages)
    selected_members: set[Path] = set()
    pending: list[Path] = []
    default_members: list[Path] = []

    for package in config.workspace_packages:
        specification = root_dependencies.get(package)
        if not isinstance(specification, Mapping) or "path" not in specification:
            raise SyncError(
                f"workspace package {package!r} has no path entry in "
                f"{config.workspace_manifest_path}"
            )
        package_path = _safe_source_path(
            specification["path"],
            description=f"workspace package {package!r}",
        )
        default_members.append(package_path)
        pending.append(package_path)

    inherited_package_fields: set[str] = set()
    inherits_lints = False
    while pending:
        member = pending.pop()
        if member in selected_members:
            continue
        if not _covered_by_mirror_path(member, config.paths):
            raise SyncError(
                f"GPUI dependency {member.as_posix()} is not covered by a configured "
                "mirror path"
            )

        manifest = _load_toml(checkout / member / "Cargo.toml")
        package_table = manifest.get("package", {})
        if not isinstance(package_table, Mapping):
            raise SyncError(f"{member / 'Cargo.toml'} has no [package] table")
        for field, value in package_table.items():
            if isinstance(value, Mapping) and value.get("workspace") is True:
                inherited_package_fields.add(field)
        lints = manifest.get("lints", {})
        if isinstance(lints, Mapping) and lints.get("workspace") is True:
            inherits_lints = True

        selected_members.add(member)
        for dependencies in _dependency_tables(manifest):
            for dependency_name, specification in dependencies.items():
                all_dependency_names.add(dependency_name)
                if not isinstance(specification, Mapping):
                    continue
                if specification.get("workspace") is True:
                    required_workspace_dependencies.add(dependency_name)
                    root_specification = root_dependencies.get(dependency_name)
                    if root_specification is None:
                        raise SyncError(
                            f"{member / 'Cargo.toml'} inherits undefined workspace "
                            f"dependency {dependency_name!r}"
                        )
                    if isinstance(root_specification, Mapping) and "path" in root_specification:
                        pending.append(
                            _safe_source_path(
                                root_specification["path"],
                                description=f"workspace dependency {dependency_name!r}",
                            )
                        )
                elif "path" in specification:
                    pending.append(_resolve_dependency_path(member, specification["path"]))

    configured_members = workspace.get("members", [])
    ordered_members: list[Path] = []
    if isinstance(configured_members, list):
        for raw_member in configured_members:
            if not isinstance(raw_member, str) or "*" in raw_member:
                continue
            member = _safe_source_path(raw_member, description="workspace member")
            if member in selected_members:
                ordered_members.append(member)
    ordered_members.extend(sorted(selected_members - set(ordered_members)))

    missing_defaults = [member for member in default_members if member not in selected_members]
    if missing_defaults:
        rendered = ", ".join(path.as_posix() for path in missing_defaults)
        raise SyncError(f"workspace package closure is missing: {rendered}")

    source_package = workspace.get("package", {})
    generated_package: dict[str, Any] = {}
    if isinstance(source_package, Mapping):
        for field, value in source_package.items():
            if field in inherited_package_fields:
                generated_package[field] = value
    missing_package_fields = inherited_package_fields - generated_package.keys()
    if missing_package_fields:
        rendered = ", ".join(sorted(missing_package_fields))
        raise SyncError(f"workspace package settings are undefined: {rendered}")

    generated_dependencies: dict[str, Any] = {}
    for dependency_name, specification in root_dependencies.items():
        if dependency_name in required_workspace_dependencies:
            generated_dependencies[dependency_name] = specification
    missing_dependencies = required_workspace_dependencies - generated_dependencies.keys()
    if missing_dependencies:
        rendered = ", ".join(sorted(missing_dependencies))
        raise SyncError(f"workspace dependencies are undefined: {rendered}")

    generated_workspace: dict[str, Any] = {
        "resolver": workspace.get("resolver", "2"),
        "members": _multiline_array([path.as_posix() for path in ordered_members]),
        "default-members": _multiline_array(
            [path.as_posix() for path in default_members]
        ),
    }
    if generated_package:
        generated_workspace["package"] = generated_package
    generated_workspace["dependencies"] = generated_dependencies
    if inherits_lints:
        source_lints = workspace.get("lints")
        if not isinstance(source_lints, Mapping):
            raise SyncError("workspace lints are inherited but [workspace.lints] is missing")
        generated_workspace["lints"] = source_lints

    generated: dict[str, Any] = {"workspace": generated_workspace}
    patches = root.get("patch")
    if isinstance(patches, Mapping):
        crates_io = patches.get("crates-io")
        if isinstance(crates_io, Mapping):
            relevant_patch_names = all_dependency_names | TRANSITIVE_GPUI_PATCHES
            relevant_patches = {
                name: value
                for name, value in crates_io.items()
                if name in relevant_patch_names
            }
            if relevant_patches:
                generated["patch"] = {"crates-io": relevant_patches}

    content = GENERATED_HEADER + tomlkit.dumps(generated)
    return GeneratedWorkspace(
        content=content,
        members=tuple(ordered_members),
        workspace_dependencies=tuple(generated_dependencies),
    )
